version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/bookhub
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    restart: always
    env_file:
      - .env
