name: Docker

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./